version: '3.8'
services:
  db:
    image: postgres:14.0
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword

  web:
    build: ./server
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - "./server:/myapp"
    ports:
      - "3000:3000"
    depends_on:
      - db
      
  frontend:
    build: ./front
    volumes:
      - ./front/dist:/usr/local/apache2/htdocs
    ports:
      - "80:80"

volumes:
  db-data: